#
# Write a pkg-config pc file for given "name" with "decription"
# Arguments:
#   name: a library name (without "lib" prefix and "so" suffixes
#   desc: a desription string
#
macro (create_pkgconfig_file name desc)
    set(_pkgfname "${CMAKE_CURRENT_BINARY_DIR}/${name}.pc")
    message(STATUS "${name}: writing pkgconfig file ${_pkgfname}")

    # Consumers of a static libvidstab have to compile with
    # VIDSTAB_STATIC_DEFINE, or the installed headers decorate the public API
    # with __declspec(dllimport) (see src/vidstab_api.h) and the link fails on
    # Windows.  Whoever links the CMake target gets this from its PUBLIC
    # compile definitions; whoever goes through pkg-config has only this file.
    if(BUILD_SHARED_LIBS)
      set(_pkg_cflags "")
    else()
      set(_pkg_cflags " -DVIDSTAB_STATIC_DEFINE")
    endif()

    file(WRITE "${_pkgfname}" "# file generated by vid.stab cmake build
prefix=${CMAKE_INSTALL_PREFIX}
libdir=${CMAKE_INSTALL_FULL_LIBDIR}
includedir=${CMAKE_INSTALL_FULL_INCLUDEDIR}

Name: ${name}
Description: ${desc}
Version: ${VIDSTAB_VERSION}
Libs: -L\${libdir} -l${name} ${PKG_EXTRA_LIBS}
Cflags: -I\${includedir}${_pkg_cflags}

")

    install(FILES ${_pkgfname} DESTINATION ${CMAKE_INSTALL_LIBDIR}/pkgconfig)
endmacro()
