#
# Write a pkg-config pc file for given "name" with "decription"
# Arguments:
#   name: a library name (without "lib" prefix and "so" suffixes
#   desc: a desription string
#
# PKG_EXTRA_LIBS holds the libraries we link against internally (-lm, OpenMP,
# an LP solver). None of them appear in the installed headers, so for a shared
# build they belong in Libs.private, where only static consumers
# (pkg-config --static) pick them up. A static libvidstab cannot resolve them
# on its own, so there they have to stay in Libs.
macro (create_pkgconfig_file name desc)
    set(_pkgfname "${CMAKE_CURRENT_BINARY_DIR}/${name}.pc")
    message(STATUS "${name}: writing pkgconfig file ${_pkgfname}")

    # Consumers of a static libvidstab have to compile with
    # VIDSTAB_STATIC_DEFINE, or the installed headers decorate the public API
    # with __declspec(dllimport) (see src/vidstab_api.h) and the link fails on
    # Windows.  Whoever links the CMake target gets this from its PUBLIC
    # compile definitions; whoever goes through pkg-config has only this file.
    set(_pkg_libs_private " ${PKG_EXTRA_LIBS}")
    if(BUILD_SHARED_LIBS)
      set(_pkg_cflags "")
      set(_pkg_libs "")
    else()
      set(_pkg_cflags " -DVIDSTAB_STATIC_DEFINE")
      set(_pkg_libs " ${PKG_EXTRA_LIBS}")
    endif()

    file(WRITE "${_pkgfname}" "# file generated by vid.stab cmake build
prefix=${CMAKE_INSTALL_PREFIX}
libdir=${CMAKE_INSTALL_FULL_LIBDIR}
includedir=${CMAKE_INSTALL_FULL_INCLUDEDIR}

Name: ${name}
Description: ${desc}
Version: ${VIDSTAB_VERSION}
Libs: -L\${libdir} -l${name}${_pkg_libs}
Libs.private:${_pkg_libs_private}
Cflags: -I\${includedir}${_pkg_cflags}

")

    install(FILES ${_pkgfname} DESTINATION ${CMAKE_INSTALL_LIBDIR}/pkgconfig)
endmacro()
