/* test_transform_incremental.c
 *
 * The planar warp does not evaluate its backward map from scratch at every
 * pixel.  Along a destination row three quantities are generated by running
 * additions instead:
 *
 *   x_s, y_s   on the plain similarity path, because dx = x_d1<<16 has no
 *              low bits, so (zcos_a*dx + zsin_xy*dy)>>16 splits exactly into
 *              zcos_a*x_d1 + (zsin_xy*dy>>16) and consecutive x_s therefore
 *              differ by exactly zcos_a
 *   r2u        wobble's undistort radius, a quadratic in x
 *   r2d        the distort radius on the plain path, likewise a quadratic
 *
 * Each claim is that the stepped sequence equals the direct expression *to
 * the bit*, over the whole row -- not that it is close.  That is a statement
 * about integer sequences, so it is tested as one, against verbatim copies of
 * the expressions the loop used before, with no frames involved.
 *
 * A quadratic needs its second difference to be constant, which it is here
 * only because every term is integer; the tests below would catch a step
 * constant that was right at x=0 and drifted, which is the way this class of
 * optimization actually fails.
 *
 * Copyright (C) Georg Martius - 2026
 *  georg dot martius at web dot de
 *
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */

/* The warp's fixed point helpers.  transformfixedpoint.c keeps these private,
   so they are restated here -- deliberately, since a test that shared them
   could not catch a change to them. */
#define tiToFp16(v) ((int32_t)((uint32_t)(v)<<16))

/* Realistic and deliberately awkward geometries.  lsx != lsy is the case that
   matters most: on 4:2:0 the two axes subsample equally, so a step constant
   that confused them would still pass. */
typedef struct {
  int      dw, dh;      /* destination plane size   */
  int      lsx, lsy;    /* luma-equivalent shifts   */
  double   alpha, zoom; /* transform                */
  double   tx, ty;
  const char* name;
} tiCase;

static const tiCase tiCases[] = {
  { 960, 540, 1, 1,  0.0261,  2.0,   7.3, -4.7, "4:2:0 chroma, small rotation" },
  { 1920,1080, 0, 0, 0.0261,  2.0,   7.3, -4.7, "luma, small rotation"         },
  { 960,1080, 1, 0,  0.0261,  2.0,   7.3, -4.7, "4:2:2 chroma, lsx!=lsy"       },
  { 1920, 540, 0, 1, 0.0261,  2.0,   7.3, -4.7, "4:4:0 chroma, lsy!=lsx"       },
  { 480,1080, 2, 0,  0.0261,  2.0,   7.3, -4.7, "4:1:1 chroma, lsx=2"          },
  { 1920,1080, 0, 0, 0.7854, 20.0, -80.0, 60.0, "luma, 45 deg and big shift"   },
  { 1920,1080, 0, 0,-0.7854,-40.0, 300.0,-250.0,"luma, -45 deg, zoomed out"    },
  { 640, 360, 1, 1,  0.0,     0.0,   0.0,  0.0, "identity"                     },
};
#define TI_NCASES ((int)(sizeof(tiCases)/sizeof(tiCases[0])))

/** x_s / y_s: the stepped affine must equal the direct expression exactly. */
void test_transform_incremental_affine(void)
{
  int c;
  for(c=0; c<TI_NCASES; c++){
    const tiCase* tc = &tiCases[c];
    double z = 1.0 - tc->zoom/100.0;
    double ax = (double)(1 << tc->lsx), ay = (double)(1 << tc->lsy);
    double zsin = z*sin(-tc->alpha);
    int32_t zcos_a  = (int32_t)((z*cos(-tc->alpha))*((double)0xFFFF));
    int32_t zsin_xy = (int32_t)((zsin*(ay/ax))*((double)0xFFFF));
    int32_t zsin_yx = (int32_t)((zsin*(ax/ay))*((double)0xFFFF));
    int32_t c_d_x = tc->dw/2, c_d_y = tc->dh/2;
    int32_t c_s_x = tiToFp16(tc->dw/2), c_s_y = tiToFp16(tc->dh/2);
    int32_t c_tx  = c_s_x - (int32_t)(tc->tx*((double)0xFFFF));
    int32_t c_ty  = c_s_y - (int32_t)(tc->ty*((double)0xFFFF));
    int rows = 0, y;

    /* every row of a real frame, not a sample of them: the row prologue is
       where an off-by-one in the starting value would hide */
    for(y=0; y<tc->dh; y++){
      int32_t y_d1 = y - c_d_y;
      int32_t dy0  = tiToFp16(y_d1);
      int32_t dx0  = tiToFp16(0 - c_d_x);
      /* the loop's row prologue, verbatim */
      int32_t xsInc = (int32_t)((( (int64_t)zcos_a *dx0 + (int64_t)zsin_xy*dy0) >> 16)) + c_tx;
      int32_t ysInc = (int32_t)(((-(int64_t)zsin_yx*dx0 + (int64_t)zcos_a *dy0) >> 16)) + c_ty;
      int x;
      for(x=0; x<tc->dw; x++){
        int32_t x_d1 = x - c_d_x;
        int32_t dx = tiToFp16(x_d1), dy = tiToFp16(y_d1);
        /* the pre-optimization expression, verbatim */
        int32_t xDirect = (int32_t)((( (int64_t)zcos_a *dx + (int64_t)zsin_xy*dy) >> 16)) + c_tx;
        int32_t yDirect = (int32_t)(((-(int64_t)zsin_yx*dx + (int64_t)zcos_a *dy) >> 16)) + c_ty;
        if(xsInc != xDirect || ysInc != yDirect){
          fprintf(stderr, "%s: affine drift at x=%d y=%d: "
                  "x %d vs %d, y %d vs %d\n",
                  tc->name, x, y, xsInc, xDirect, ysInc, yDirect);
          test_bool(xsInc == xDirect);
          test_bool(ysInc == yDirect);
          return;
        }
        xsInc += zcos_a;
        ysInc -= zsin_yx;
      }
      rows++;
    }
    printf("  affine exact over %d rows x %d px: %s\n", rows, tc->dw, tc->name);
    test_bool(rows == tc->dh);
  }
  return;
}

/** r2u: wobble's undistort radius, stepped as a quadratic in x. */
void test_transform_incremental_r2u(void)
{
  int c;
  for(c=0; c<TI_NCASES; c++){
    const tiCase* tc = &tiCases[c];
    int32_t c_d_x = tc->dw/2, c_d_y = tc->dh/2;
    int y, checked = 0;
    for(y=0; y<tc->dh; y++){
      int32_t y_d1 = y - c_d_y;
      /* row prologue, verbatim */
      int64_t Lx  = (int64_t)1 << (16 + tc->lsx);
      int64_t lx0 = (int64_t)tiToFp16(0 - c_d_x) * (1 << tc->lsx);
      int64_t ly0 = (int64_t)tiToFp16(y_d1)      * (1 << tc->lsy);
      int64_t r2u      = lx0*lx0 + ly0*ly0;
      int64_t r2uStep  = 2*lx0*Lx + Lx*Lx;
      int64_t r2uStep2 = 2*Lx*Lx;
      int x;
      for(x=0; x<tc->dw; x++){
        int32_t x_d1 = x - c_d_x;
        int32_t dx = tiToFp16(x_d1), dy = tiToFp16(y_d1);
        /* pre-optimization expression, verbatim */
        int64_t lx = (int64_t)dx * (1 << tc->lsx), ly = (int64_t)dy * (1 << tc->lsy);
        int64_t direct = lx*lx + ly*ly;
        if(r2u != direct){
          fprintf(stderr, "%s: r2u drift at x=%d y=%d: %lld vs %lld\n",
                  tc->name, x, y, (long long)r2u, (long long)direct);
          test_bool(r2u == direct);
          return;
        }
        r2u     += r2uStep;
        r2uStep += r2uStep2;
        checked++;
      }
    }
    printf("  r2u exact over %d px: %s\n", checked, tc->name);
    test_bool(checked == tc->dw * tc->dh);   /* the loop actually ran */
  }
  return;
}

/** r2d: the distort radius on the plain path, where x_s and y_s are affine. */
void test_transform_incremental_r2d(void)
{
  int c;
  for(c=0; c<TI_NCASES; c++){
    const tiCase* tc = &tiCases[c];
    double z = 1.0 - tc->zoom/100.0;
    double ax = (double)(1 << tc->lsx), ay = (double)(1 << tc->lsy);
    double zsin = z*sin(-tc->alpha);
    int32_t zcos_a  = (int32_t)((z*cos(-tc->alpha))*((double)0xFFFF));
    int32_t zsin_xy = (int32_t)((zsin*(ay/ax))*((double)0xFFFF));
    int32_t zsin_yx = (int32_t)((zsin*(ax/ay))*((double)0xFFFF));
    int32_t c_d_x = tc->dw/2, c_d_y = tc->dh/2;
    int32_t c_s_x = tiToFp16(tc->dw/2), c_s_y = tiToFp16(tc->dh/2);
    int32_t c_tx  = c_s_x - (int32_t)(tc->tx*((double)0xFFFF));
    int32_t c_ty  = c_s_y - (int32_t)(tc->ty*((double)0xFFFF));
    int y, checked = 0;
    for(y=0; y<tc->dh; y++){
      int32_t y_d1 = y - c_d_y;
      int32_t dy0  = tiToFp16(y_d1);
      int32_t dx0  = tiToFp16(0 - c_d_x);
      int32_t xsInc = (int32_t)((( (int64_t)zcos_a *dx0 + (int64_t)zsin_xy*dy0) >> 16)) + c_tx;
      int32_t ysInc = (int32_t)(((-(int64_t)zsin_yx*dx0 + (int64_t)zcos_a *dy0) >> 16)) + c_ty;
      /* row prologue, verbatim */
      int64_t lx0 = (int64_t)(xsInc - c_s_x) * (1 << tc->lsx);
      int64_t ly0 = (int64_t)(ysInc - c_s_y) * (1 << tc->lsy);
      int64_t dlx = (int64_t)zcos_a   * (1 << tc->lsx);
      int64_t dly = -(int64_t)zsin_yx * (1 << tc->lsy);
      int64_t r2d      = lx0*lx0 + ly0*ly0;
      int64_t r2dStep  = 2*lx0*dlx + dlx*dlx + 2*ly0*dly + dly*dly;
      int64_t r2dStep2 = 2*(dlx*dlx + dly*dly);
      int x;
      for(x=0; x<tc->dw; x++){
        int32_t x_d1 = x - c_d_x;
        int32_t dx = tiToFp16(x_d1), dy = tiToFp16(y_d1);
        int32_t x_s = (int32_t)((( (int64_t)zcos_a *dx + (int64_t)zsin_xy*dy) >> 16)) + c_tx;
        int32_t y_s = (int32_t)(((-(int64_t)zsin_yx*dx + (int64_t)zcos_a *dy) >> 16)) + c_ty;
        /* pre-optimization expression, verbatim */
        int64_t ex = x_s - c_s_x, ey = y_s - c_s_y;
        int64_t lx = ex * (1 << tc->lsx), ly = ey * (1 << tc->lsy);
        int64_t direct = lx*lx + ly*ly;
        if(r2d != direct){
          fprintf(stderr, "%s: r2d drift at x=%d y=%d: %lld vs %lld\n",
                  tc->name, x, y, (long long)r2d, (long long)direct);
          test_bool(r2d == direct);
          return;
        }
        r2d     += r2dStep;
        r2dStep += r2dStep2;
        checked++;
      }
    }
    printf("  r2d exact over %d px: %s\n", checked, tc->name);
    test_bool(checked == tc->dw * tc->dh);   /* the loop actually ran */
  }
  return;
}

/* The largest intermediate is the squared radius in 16.16 luma-equivalent
   units.  The <<lsx / <<lsy convert a plane offset back to luma, so a chroma
   plane's contribution is bounded by the LUMA dimension however deeply it is
   subsampled -- 4:1:1 has a quarter-width plane and lsx = 2, which cancel.
   The bound is therefore set by the frame, not by the format.

   Coordinates do leave the frame: zooming out and translating push x_s past
   the border, which is exactly when the correction matters.  Allow a generous
   4x half-frame excursion on both axes.  (VS_LENS_OUTSIDE_PX is far larger
   still, but it is assigned after r2 is computed and never feeds back into
   it -- the stepped r2d comes from the affine, not from the value the domain
   test may have replaced.)

   This bound is shared with the direct expression the loop used before; the
   stepping does not widen it, since it generates the same values. */
void test_transform_incremental_range(void)
{
  const int64_t lumaHalf  = 3840;                    /* 8K wide (7680) */
  const int64_t excursion = 4;
  int64_t worstCoord = (int64_t)tiToFp16(lumaHalf * excursion);
  int64_t worstR2    = 2 * worstCoord * worstCoord;
  printf("  8K frame, %lldx half-frame excursion: worst r2 %lld,"
         " int64 max %lld (%.0fx headroom)\n",
         (long long)excursion, (long long)worstR2, (long long)INT64_MAX,
         (double)INT64_MAX/(double)worstR2);
  test_bool(worstCoord > 0);              /* the 16.16 coordinate itself fits */
  test_bool(worstR2 > 0);                 /* the square did not wrap          */
  /* ~5x at this deliberately extreme setting (8K with a 4x excursion, i.e.
     coordinates four half-frames outside the picture).  Real clips are orders
     of magnitude inside it; the assertion is here so that a future format or
     frame size that eats the margin fails loudly rather than wrapping into a
     negative radius and reading garbage from the LUT. */
  test_bool(worstR2 < INT64_MAX/4);

  /* The step constants are smaller than the value they step, so if the
     quadratic fits, so do they. */
  {
    int64_t Lx = (int64_t)1 << (16 + 2);  /* the largest shift any format uses */
    test_bool(2*Lx*Lx > 0);
    test_bool(2*Lx*Lx < worstR2);
  }
}

/*
 * Local variables:
 *   c-file-style: "stroustrup"
 *   c-file-offsets: ((case-label . *) (statement-case-intro . *))
 *   indent-tabs-mode: nil
 *   c-basic-offset: 2 t
 * End:
 *
 * vim: expandtab shiftwidth=2:
 */
