#!/bin/sh
# Build the benchmark. Extra compiler flags can be passed as arguments.
set -e
cd "$(dirname "$0")/.."
SRCS="src/frameinfo.c src/transformtype.c src/libvidstab.c src/transform.c \
src/transformfixedpoint.c src/motiondetect.c src/motiondetect_opt.c \
src/serialize.c src/localmotion2transform.c src/boxblur.c src/vsvector.c \
src/l1campathoptimization.c src/lpsolver_ipm.c src/cpudetect.c \
src/motiondetect_dispatch.c src/lensmap.c src/lensdistortion.c"

mkdir -p bld

# libvidstab_version.h is generated by CMake from version.cmake; do the same
# substitution here so this script does not need a CMake tree to exist.
sed -e "s/@MAJOR_VERSION@/$(sed -n 's/^set(MAJOR_VERSION \([0-9]*\)).*/\1/p' version.cmake)/g" \
    -e "s/@MINOR_VERSION@/$(sed -n 's/^set(MINOR_VERSION \([0-9]*\)).*/\1/p' version.cmake)/g" \
    -e "s/@PATCH_VERSION@/$(sed -n 's/^set(PATCH_VERSION \([0-9]*\)).*/\1/p' version.cmake)/g" \
    src/libvidstab_version.h.in > bld/libvidstab_version.h

# -msse2 -ffast-math are what the library is actually built with (CMakeLists.txt),
# and the transform code reasons about -ffinite-math-only explicitly, so the
# benchmark has to see the same flags or it is not measuring the shipped code.
BASE="-O3 -std=gnu99 -msse2 -ffast-math -Isrc -Ibld"

# The wide kernels get their own -m flags, exactly as CMake does per source.
gcc $BASE -c src/motiondetect_avx2.c   -o bld/mdavx2.o   -DVS_HAVE_AVX2 -mavx2 "$@"
gcc $BASE -c src/motiondetect_avx512.c -o bld/mdavx512.o -DVS_HAVE_AVX512 \
    -mavx512f -mavx512bw -mavx512vl "$@"
# NEON kernel, built for x86 against the scalar emulation so it can be checked here
gcc $BASE -Itests -c src/motiondetect_neon.c -o bld/mdneon.o \
    -DVS_HAVE_NEON -DVS_NEON_EMULATION "$@"
OBJS="bld/mdavx2.o bld/mdavx512.o bld/mdneon.o"
EXTRA_DEFS="-DVS_HAVE_AVX2 -DVS_HAVE_AVX512 -DVS_HAVE_NEON"
gcc $BASE -DUSE_OMP -fopenmp -DUSE_IPM -DVS_HAVE_LPSOLVER \
    $EXTRA_DEFS -Itests -o bld/bench bench/bench_motiondetect.c $SRCS $OBJS -lm "$@"

# The transform benchmark. -DTESTING keeps the float implementation under its
# own name, so both can be timed (and compared) in one binary.
gcc $BASE -DUSE_OMP -fopenmp -DUSE_IPM -DVS_HAVE_LPSOLVER -DTESTING \
    $EXTRA_DEFS -Itests -o bld/bench_transform bench/bench_transform.c \
    $SRCS src/transformfloat.c $OBJS -lm "$@"
